### PR TITLE
Fix test failure

### PR DESCRIPTION
**Pull request by Amalraj-Joseph-IBM**
https://github.com/OpenLiberty/sample-getting-started/issues/137

### CODE REVIEW

**Comment by Amalraj-Joseph-IBM** [comment]
Hi @leochr ,
I just opened the PR as I thought this was relatively simple, and I thought I could make a contribution here.
I corrected the reference to the resource file, but even after that, a test case was failing, and I found it was a timeout when switching the service(/health) between UP and DOWN. So, I increased the Thread.sleep() value from 600, and I started to get consistent results at 1500.
To check if it is something related to my local setup, I checked out a previous commit ([6ec559](https://github.com/OpenLiberty/sample-getting-started/commit/6ec55926946b6f5c2238c82a9d0e671d2c5b728c)) and found 600 was working fine there. So I doubt some recent changes may have affected the app's performance (perhaps I'm wrong). Is it something to be concerned about?

**Comment by leochr** [comment]
@Amalraj-Joseph-IBM Thanks for taking a look at the issue and the PR. The changes look good to me.

As for the timeout, I am not sure. @fmhwong the Health-related tests work fine with `mpMetrics-5.0` and `mpConfig-3.0` but consistently fail with `mpMetrics-5.1` and `mpConfig-3.1` [when Thread.sleep(600) is used]. Is this a known performance degradation?

**Comment by fmhwong** [comment]
We haven't updated mpHealth for a while.  No sure if the server was slow to update the configuration.  @pgunapal Can you take a look?

**Comment by leochr** [comment]
Thank you all! I'll go ahead with approval and merge the PR.

**Review by leochr — APPROVED** [review]

**Pull request merged**
